### ISSUE TITLE
Automatically calculate "id"

### ISSUE THREAD

**Issue by jml** [weaveworks/grafanalib#1]
Currently, Graphs have to specify their ID. Ideally, the generator would just populate this uniquely.

Fixing this probably requires a shift in our internals. Rather than returning the "rendered" JSON dict we should return a custom object (e.g. a `Graph` type) with a `toJSON` method. When we have such objects, it will be fairly easy to add a post-processing stage to insert ID.

**Comment by jml** [comment]
#17 is the "shift in our internals" referred to in the original post.

**Comment by dmajere** [comment]
We can traverse rows and panels in `Dashboard` class `to_json_data` and set `id` fields for every panel there before returning json object.

**Comment by dmajere** [comment]
Here is a PR for it #32
