### ISSUE TITLE
grafanlib didn't work due to "No module named machinery"

### ISSUE THREAD

**Issue by mrsiano** [weaveworks/grafanalib#112]
Is grafanalib supports python7.2 ?!
grafnalib were installed via pip install grafanalib 
when running grafanalib, 'm facing this:
generate-dashboard -o frontend.json frontend.dashboard.py
Traceback (most recent call last):
  File "/usr/bin/generate-dashboard", line 9, in <module>
    load_entry_point('grafanalib==0.4.0', 'console_scripts', 'generate-dashboard')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/grafanalib/_gen.py", line 7, in <module>
    from importlib.machinery import SourceFileLoader
ImportError: No module named machinery

I just exeect the grafnalib to run as described

looks like it didn't worked for py27
pip install py2exe
    RuntimeError: This package requires Python 3.3 or later
see also https://stackoverflow.com/questions/24237385/no-module-named-machinery

**Comment by jml** [comment]
The released version only supports Python 3. The version in master supports 2.7 as well. We hope to release a new version shortly.

**Comment by mrsiano** [comment]
thanks

**Comment by mrsiano** [comment]
there is some documentation about how to use master?

**Comment by jml** [comment]
Not really. It's the same as using any other Python package from source.

Download the source, and then run `pip install .` inside the directory.
