### ISSUE TITLE
Support influxDB datasource?

### ISSUE THREAD

**Issue by ondrejFuchs** [weaveworks/grafanalib#122]
I would like to ask is there a support for influxdb datasource?  And if possible, what  would look like `Target(
            expr='<Influxdb data source ?>',
            legendFormat="1xx",
            refId='A',
          ),`
Thanks for response.

**Comment by jml** [comment]
We have support for any kind of data source, but nothing specific for influxdb. 

I don't have any experience with influxdb myself, so can't answer your question.

**Comment by ondrejFuchs** [comment]
I work with Grafana, influxDB and telegraf. Telegraf as agent send data to influxDB and after these I visualize it in Grafana (like CPU). I wanted to wrote my dashboard with grafanalib and sent to Grafana Api, but I don't know if its possible. So you don't have experiences with grafana and InfluxDB (specifically load data from influxdb to set graphs using grafanalib)? Thanks for response.

**Comment by MahadevG** [comment]
I do have same query that can we use grafanalib with influxdb??
I tried with influx db graph is getting created but expression is not showing in grafana.

Any workaround for this??

**Comment by buroa** [comment]
Probably fixed with my issue and PR #145

**Comment by rdroll7** [comment]
Was this indeed fixed with PR#145?  

Does anyone have a small example that correctly sets the query?

**Comment by qmnonic** [comment]
Linked PR will fix it.  Needs to be a raw query vs the wysiwyg 

https://github.com/weaveworks/grafanalib/pull/182

**Comment by dholbach** [comment]
Fixed!
