### ISSUE TITLE
Grafana 5 compatibility

### ISSUE THREAD

**Issue by leth** [weaveworks/grafanalib#123]
I'm starting this to track Grafana 5 compatibility issues as we find them, we could break them out into multiple issues later?

- ~[Dashboard `uid` required for consistent URLs](https://github.com/grafana/grafana/issues/11013) #125~
- Rows without titles show a title of "New Row"
- Heatmap Panels

**Comment by lukas-vlcek** [comment]
May be this can help: [grafana/grafana/blob/master/public/app/features/dashboard/dashboard_migration.ts](https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashboard_migration.ts).

As of writing the grafanalib produces dashboards with `schemaVersion: 12`. Upgrading to Grafana 5.x will probably need to cover parts within conditions `if (oldVersion < 14) ...` and `if (oldVersion < 16) ...`.

**Comment by matthewmrichter** [comment]
Wondering if this issue is worth keeping open. Are a lot of people still using Grafana 5 at this point? If so, any compatibility issues we should track?

**Comment by leth** [comment]
We opened this issue when grafana 5.x was relatively new, so the intent was to track things that needed fixing for people who upgrade to the current release, not backwards compatibility issues.
Feel free to close!
