### ISSUE TITLE
Automatic refId generator

### ISSUE THREAD

**Issue by vthriller** [weaveworks/grafanalib#128]
I'd really like to see one, similarly to now `auto_panel_ids()` currently work: I just don't care about `refId`s most of the time, yet omitting them (just like in that minimal example below) causes all sorts of weird problems on grafana side, like in 5.1.3 where sibling graphs with empty `refId`s render nothing but loading spinner up until query inspector is opened.

```python
dashboard = Dashboard(
        title = 'testing testing 123',
        rows = [
                Row(panels = [
                        Graph(
                                title = 'zomg constants',
                                dataSource = 'prometheus',
                                targets = [
                                        Target(expr = '1'),
                                        Target(expr = '2'),
                                ],
                        ),
                ]),
        ],
).auto_panel_ids()
```

**Comment by jml** [comment]
I think this is a valid request. In the meantime, you might want to look at something like `PromGraph`.

**Comment by daveworth** [comment]
I've given this enhancement a shot and it wasn't too bad - I hope folks like it and it helps them.

**Comment by JamesGibo** [comment]
Added in #144
