### ISSUE TITLE
Question:  How many types of panel does grafanalib support?

### ISSUE THREAD

**Issue by jinh-dk** [weaveworks/grafanalib#131]
The example only shows that grafanalib supports Graph panel,  does it also support other types, like singlestat, heatmap?

Thanks.

**Comment by jml** [comment]
I don't know off the top of my head.

Best way to find out is to skim through the `core.py` module and look for
things that look like they might be panels.

**Comment by JamesGibo** [comment]
Release notes is also a useful place to look.
