### ISSUE TITLE
Question: Would you consider tagging a new release so we can get hold of the uid functionality?

### ISSUE THREAD

**Issue by cloudshapes** [weaveworks/grafanalib#136]
Current commits post the 0.5.1 release have: `version='0.5.0'` ... which makes it a little difficult to pull commits via `python setup.py` that enable the `uid` functionality (v useful in grafana-5).

So, I was wondering if you'd consider tagging another release `0.5.2`, which would make that much more straightforward?

Thanks,
Roland

**Comment by jml** [comment]
Yes, definitely something I want to do soon.

**Comment by cloudshapes** [comment]
Great, thanks, that would be v helpful.

**Comment by jml** [comment]
Done!

**Comment by cloudshapes** [comment]
That's great, thanks v much!
