### ISSUE TITLE
Question: Is there any way to specify the size of panels?

### ISSUE THREAD

**Issue by littleJabiel** [weaveworks/grafanalib#139]
Hi everyone, I'm creating dashboards using grafanalib but there is no way to specify size or position in a specific panel. I tried to create my own class with a gridPos object (x and y position and height and width attributes) and I'm able to generate a json with correct gridPos but anyway it doesn't work. 

Am I doing something wrong? please help

**Comment by jml** [comment]
Hi!

I'm afraid I can't help. If you prepare a short, self-contained, correct
example (c.f. http://sscce.org/), share it here, along with screenshots of
what you see, a description of what you expect to see, and a clear
articulation of the difference, then perhaps I or someone else would be
able to help.

cheers,
jml

**Comment by hugobcar** [comment]
We are with the same problem. I can't add `GridPos` at Json generated from Grafanalib.
