### ISSUE TITLE
Cloudwatch datasources not supported due to Target class restrictions

### ISSUE THREAD

**Issue by buroa** [weaveworks/grafanalib#145]
There is no support for Cloudwatch since the Target class has restrictions. If you remove them, you'll be able to make Cloudwatch graphs.

**Comment by KaoSiTo** [comment]
Please, add CloudWatch support :)

**Comment by o-be-one** [comment]
+1!

**Comment by uritau** [comment]
Hello! 
I have the same needs as you, so I added the Cloudwatch Target, it will be awesome if you can test and suggest any improvement.
You can see the code here, in this [PR](https://github.com/weaveworks/grafanalib/pull/184).

Thanks for your (constructive) feedback!
