### ISSUE TITLE
Feature Request: support sql queries

### ISSUE THREAD

**Issue by vbichov** [weaveworks/grafanalib#153]
Grafana supports mysql queries out of the box.

**Comment by akshayah3** [comment]
@vbichov Were you able to execute sql queries?

**Comment by vbichov** [comment]
yes - I forked the repo and added the missing code:
https://github.com/vbichov/grafanalib/blob/master/grafanalib/core.py#L393

**Comment by Valiev** [comment]
+1 for the support

**Comment by JamesGibo** [comment]
@vbichov do you want to submit a PR to add support for this to main repo?

**Comment by gardlt** [comment]
Can I make a PR against this?

**Comment by rjulius23** [comment]
Ok so nobody did that so I will open it :)

**Comment by rjulius23** [comment]
@JamesGibo can you please check it out ? #firsttimemaintainerhere :)

**Comment by JamesGibo** [comment]
Closed in #429 
Thanks @rjulius23

**Comment by rjulius23** [comment]
@JamesGibo when do you think it can be released ? It would be neat to have soon :)

**Comment by JamesGibo** [comment]
@rjulius23 new release should now be published. Thanks again for your PR
