### ISSUE TITLE
where did grafanalib 0.5.3 come from?

### ISSUE THREAD

**Issue by BenJTucker** [weaveworks/grafanalib#157]
## What you expected to happen?
I expected to find the code for the latest release listed in pypi (0.5.3) in github.
## What happened?
The current version is in github appears to be 0.5.2. That is the version stated in setup.py in master and also where the changelog ends. Did a branch for 0.5.3 get deleted without being merged to master, or is it hiding somewhere else?

## How to reproduce it?
    $ pip install grafanalib
    ...
    $ pip freeze |grep grafanalib
    grafanalib==0.5.3

**Comment by vbichov** [comment]
tag?
https://github.com/weaveworks/grafanalib/commits/v0.5.3

**Comment by Atem18** [comment]
@BenJTucker As you can see on the setup : https://github.com/weaveworks/grafanalib/blob/master/setup.py and now the changelog : https://github.com/weaveworks/grafanalib/blob/master/CHANGELOG.rst, version 0.5.3 is ok. You can close the issue.
