### ISSUE TITLE
Feature: support "thresholds" in Graph

### ISSUE THREAD

**Issue by oxddr** [weaveworks/grafanalib#171]
## What you expected to happen?
Graph doesn't support [thresholds](https://grafana.com/docs/features/panels/graph/#thresholds)

## What happened?

I wanted to specify a threshold for a graph, but it seems [Graph](https://github.com/weaveworks/grafanalib/blob/master/grafanalib/core.py) class doesn't support it. 

## How to reproduce it?

N/A

This seems to be a minor change, so unless there is ongoing work to add this I'll try to send PR soon.

**Comment by dholbach** [comment]
@oxddr This sounds great. If you'd be up for writing a PR, that'd be very welcome.

**Comment by oxddr** [comment]
I don't think I'll find time to code this anytime soon unfortunately :(

**Comment by dholbach** [comment]
@oxddr No worries. Thanks very much in any case!

**Comment by JamesGibo** [comment]
If you are referring to adding alerting thresholds to Graphs this is already supported using `AlertCondition` object
https://github.com/weaveworks/grafanalib/blob/4c56c8f7d41e516dc2e5ab2e7df567ebcfaff16c/grafanalib/core.py#L908

```
alert = core.Alert(
        name= 'Alert name',
        message= "The Alert message",
        alertConditions= [core.AlertCondition(
            target= targets[0],
            evaluator= core.GreaterThan(0.9*16.0),
            timeRange= core.TimeRange(from_time='30m', to_time='now'),
            operator= core.OP_AND,
            reducerType= core.RTYPE_AVG,
            type='query'
        )],
        executionErrorState='alerting',
        frequency='2m', handler=1,
        noDataState='no_data',
        gracePeriod='10m'
    )

    panel = core.Graph(
        title="Graph name",
        description="Graph used to generate alerts",
        dataSource='prometheus',
        targets=targets,
        yAxes=core.YAxes(core.YAxis(label="", format="amp")),
        alert=alert
    )
```

**Comment by JamesGibo** [comment]
Thanks, i have created a PR to add support for this to the graph panel
