### ISSUE TITLE
Feature: Hidden targets

### ISSUE THREAD

**Issue by Mrngilles** [weaveworks/grafanalib#173]
## What you expected to happen?
Having the possibility to hide queries, so that they can be used for alerting

## What happened?
The `hide` field is not defined

It is possible that this is because it was not in the `schemaVersion: 12`, which I understand this library creates the JSON in.

**Comment by JamesGibo** [comment]
The target class includes the hide field
https://github.com/weaveworks/grafanalib/blob/master/grafanalib/core.py#L373

Hope this helps
