### ISSUE TITLE
v0.5.4 not exists in PyPI

### ISSUE THREAD

**Issue by samjo-nyang** [weaveworks/grafanalib#174]
## What you expected to happen?
- https://pypi.org/project/grafanalib/#history
- https://github.com/weaveworks/grafanalib/releases/tag/v0.5.4
The recent version on the pypi page is v0.5.3, not v0.5.4

**Comment by bboreham** [comment]
Can someone explain how to fix this?

**Comment by samjo-nyang** [comment]
Just login to PyPI, and upload the v0.5.4 package

**Comment by butlerx** [comment]
this appears to be a reacurring issue of packages not being uploaded to pypi, some ci/cd to upload tagged releases would be super nice

**Comment by dholbach** [comment]
Sorry for the delay everyone. I just uploaded 0.5.4. Feedback if this works as intended would be much appreciated.

**Comment by dholbach** [comment]
Pinging everyone on this thread: @butlerx @mridsole @matthewmrichter @filippog @samjo-nyang @bboreham

**Comment by dholbach** [comment]
Yeah, I was thinking of following the steps on https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ once I have access to the controls and potentially get out [0.5.5](https://github.com/weaveworks/grafanalib/milestone/2) as a test.

cc @matthewmrichter and @bboreham

**Comment by samjo-nyang** [comment]
Thanks!

**Comment by filippog** [comment]
Looks great, thanks @dholbach !

**Comment by dholbach** [comment]
[0.5.5](https://github.com/weaveworks/grafanalib/releases/tag/v0.5.5) is out now too.
