### ISSUE TITLE
specify what version of Grafana is supported

### ISSUE THREAD

**Issue by dimitropoulos** [weaveworks/grafanalib#176]
## What you expected to happen?
When I view the documentation (perhaps including the changelog, but more often than not just the main readme) I expect to see some information about what version of grafana is supported.

## What happened?
I was not able to find any documentation on what version of grafana is known to work.

**Comment by matthewmrichter** [comment]
I'll do some research into the footprint around versions. Speaking for my organization, we are running mainly 6.3.x clusters.

**Comment by matthewmrichter** [comment]
I understand that the grafana schema versions are forward-compatible. However Grafanalib will generally be pegged to a Grafana Schema version. We will add some documentation about the currently supported schema version.

**Comment by marcusolsson** [comment]
Strictly speaking, schemas are not forward-compatible themselves. However, Grafana migrates the dashboard to the latest version when they're loaded. Meaning, schemas may introduce breaking changes, but you'll still be able to import a dashboard from Grafana 2.0 to 7.0.
