### ISSUE TITLE
Template Class does not allow for specifying options for custom type

### ISSUE THREAD

**Issue by ljades** [weaveworks/grafanalib#188]
## What you expected to happen?
Template class should have an `options` attribute to specify specific env variable names for custom type.

## What happened?

`options` is always populated with an empty list.

**Comment by matthewmrichter** [comment]
Seems like we should provide the capability to override the `options` here: 

https://github.com/weaveworks/grafanalib/blob/06d570d4b0a47f01407b497289d8ba9305b02587/grafanalib/core.py#L683

A workaround we have been using, which isn't very elegant at all, is to pass json to the Dashboard `templating` attribute, like this:

```
        templating=Templating(list([
            {
                "auto": False,
                "auto_count": 30,
                "auto_min": "10s",
                "current": {
                    "text": "2m",
                    "value": "2m"
                },
                "hide": 0,
                "label": "interval",
                "name": "interval",
                ...
```

**Comment by JamesGibo** [comment]
Support for this was added in #143
