### ISSUE TITLE
Not possible to set options in Template for simple custom variable

### ISSUE THREAD

**Issue by VatslauX** [weaveworks/grafanalib#194]
'options': [],
in core.py
 Suggest to 
add setter
 options = attr.ib(default=[])
an replace
 'options': [], ->  'options': self.options,

Bu probably need to wrap
inner objects
"options": [
      {
        "selected": false,
        "text": "1.9*",
        "value": "1.9*"
      },]

**Comment by JamesGibo** [comment]
Support for this was added in #143
