### ISSUE TITLE
Specifying two Y axes is cumbersome

### ISSUE THREAD

**Issue by jml** [weaveworks/grafanalib#2]
Lots of graphs have configuration like:

```python
        yAxes=[
          YAxis(format=OPS_FORMAT),
          YAxis(format=SHORT_FORMAT),
        ],
```

The second Y axis isn't very interesting at all. If it's not interesting, we shouldn't have to configure it.

**Comment by dmajere** [comment]
I think that we can change `Graph` class this way:

```
class Graph(object):
...
fields
...
yAxis = attr.ib(default=attr.Factory(YAxis), validator=instance_of(YAxis))
secondaryYAxis = attr.ib(default=None)
```

And if `secondaryYAxis` is `None` we'll return 

```
        yAxes=[self. yAxis, self. yAxis]
```
else 
```
        yAxes=[self. yAxis, self. secondaryYAxis]
```

**Comment by jml** [comment]
I would much rather have a wrapper. I really like the way the core objects reflect the grafanalib data structure directly. 

It might be though that this is a compromise worth making. Am not sure.
