### ISSUE TITLE
Links should be an object

### ISSUE THREAD

**Issue by matthewmrichter** [weaveworks/grafanalib#210]
## What you expected to happen?
We should have a `Links` class defined for the optional dashboard links in the top right.

Current workaround is to paste the links in JSON Model format:

```
    return Dashboard(
        title="Grafana Metrics",
        links=[
            {
            "icon": "external link",
            "tags": [],
            "targetBlank": True,
            "title": "Available metrics",
            "type": "link",
            "url": "/metrics"
            },
            {
            "icon": "external link",
            "tags": [],
            "title": "Grafana docs",
            "type": "link",
            "url": "http://docs.grafana.org/"
            },
            {
            "icon": "external link",
            "tags": [],
            "title": "Prometheus docs",
            "type": "link",
            "url": "http://prometheus.io/docs/introduction/overview/"
            }
        ],
...
```

**Comment by JamesGibo** [comment]
There is some support for this with the following classes
https://github.com/weaveworks/grafanalib/blob/1d55608760d982f76f6c446373e4d8774d04da17/grafanalib/core.py#L646-L665

And

https://github.com/weaveworks/grafanalib/blob/1d55608760d982f76f6c446373e4d8774d04da17/grafanalib/core.py#L668-L690

**Comment by dholbach** [comment]
@matthewmrichter (and everyone else who requested this): ^ does this suit you - do you need anything else?

**Comment by JamesGibo** [comment]
Closing due to no further comments, feel free to re-open if I have missed something
