### ISSUE TITLE
Missing links to docs

### ISSUE THREAD

**Issue by sparkiegeek** [weaveworks/grafanalib#214]
## What you expected to happen?
* See link to docs on GitHub README
* See link to docs on PyPi page
## What happened?
* No doc links
* Manually found them at https://grafanalib.rtfd.org/

## How to reproduce it?
* Visit https://github.com/weaveworks/grafanalib/ and try to find docs
* Visit https://pypi.org/project/grafanalib/ and try to find docs

**Comment by dholbach** [comment]
Thanks for the feedback @sparkiegeek !

There's a link in https://github.com/weaveworks/grafanalib/blame/master/README.rst#L109 but I'll add another one in the "get help" section. I'll see to adding it to PyPI too.

**Comment by sparkiegeek** [comment]
Ah, so there is, somehow my eyes missed it. I was looking for a badge - https://docs.readthedocs.io/en/stable/badges.html

**Comment by dholbach** [comment]
Sweet. I'll get one of those added too!
