### ISSUE TITLE
PROPOSAL: classes refactor

### ISSUE THREAD

**Issue by dmajere** [weaveworks/grafanalib#23]
This one is intended to start a discussion, here is my proposal:

All the classes must have `to_json_data` method, so it's a good idea to factor it out in a parent class.

It can be something like this:

```
@attr.s
class JsonObject(object):

    def to_json_data(self):
        return dict(
            (a.name, getattr(self, a.name))
            for a in self.__attrs_attrs__ if getattr(self, a.name) is not None)
```

we'll have one major problem with this approach: it seams that there is no hard rule on grafana json fields naming. some fields are in camelcase, some are in snakecase.
So, we can either keep class field names equal to grafana json names, or introduce some kind of mapping, like this:

```
@attr.s
class JsonObject(object):
    FIELD_MAPPING = {
        'dataSource': 'datasource'
    }

    def get_field_mapping(self, field):
        return self.FIELD_MAPPING.get(field, field)

    def to_json_data(self):
        return dict(
            (self.get_field_mapping(a.name), getattr(self, a.name))
            for a in self.__attrs_attrs__ if getattr(self, a.name) is not None)
```

**Comment by jml** [comment]
Interesting! Thanks for proposing this.

Some thoughts:

* I'm going to insist on consistent naming style for Python variables / fields
* I'd like to [avoid subclassing](https://www.youtube.com/watch?v=3MNVP9-hglc) if we can. One way we could do this is to rely on attrs to inspect fields:

    ```python
    def to_json_data(obj):
      return attr.asdict(obj)
    ```

   If we are worried about objects defining attributes that aren't part of the Grafana JSON schema (and we should be), then we can filter based on some metadata (see below). Another way is to have a class decorator, but I think that's unnecessary.
* I'm uncertain about automating this away:
  * PRO: less duplication, thus less scope for silly errors
  * CON: less explicit, which increases scope for difficult-to-understand errors
  * Do you have any more pros & cons?
* attrs allows attributes to [specify a `metadata` field](https://attrs.readthedocs.io/en/stable/api.html#attr.ib), perhaps we can use this to store the Grafana field mapping, e.g.

    ```python
    @attr.s
    class Graph(object):
      dataSource = attr.ib(metadata={'grafanaName': 'datasource'})
    ```
* We could even wrap this in a helper, `grafanaField`, so we can explicitly mark attributes as being exported

What do you think?

**Comment by dmajere** [comment]
I totally agree with keeping fields naming in python consistent.

I like attr metadata approach much better then the one I've proposed before, It will make code much more declarative, so it should become more readable.

I don't think that factoring out `to_json_data` will lead to any additional complexity, we will only separate behaviour from data.
On the other hand, someone would probably like to create subclasses for panel, targets (they can differ depending on datasource), etc. And in this case, I think you're right - it's better to define all the fields explicitly for every panel class, even it they all have some common fields like id, datasource etc.
