### ISSUE TITLE
Grafana schema has changed to Schema 22

### ISSUE THREAD

**Issue by rohanmohapatra** [weaveworks/grafanalib#250]
## What you expected to happen?
Once I create a dashboard, panels allowed rows, after opening it on Grafana, the panel structure had changed. Any update would cause breaking changes as Row is not supported by grafana any more.
## What happened?
Is there a plan on how to move the new Schema Version?

**Comment by dholbach** [comment]
AFAIUI some work has been put into fixing this in https://github.com/weaveworks/grafanalib/pull/172

**Comment by matthewmrichter** [comment]
There is some tech debt to be addressed for compatibility with the newer Grafana versions that may or may not break compatibility with older Grafana versions. We set up the 0.6.0 milestone in this project to address that. This feels like it will fit with that.

**Comment by robobeaver6** [comment]
Is there a rough ETA for 0.6.0?   Eagerly awaiting GridPos support.

**Comment by JamesGibo** [comment]
Not currently, GridPos is something I would like to add as well but not had time yet.

Looks as though Grafana is looking to start publishing its schemas
https://github.com/grafana/grafana/tree/master/dashboard-schemas
