### ISSUE TITLE
Singlestat links are broken

### ISSUE THREAD

**Issue by dholbach** [weaveworks/grafanalib#251]
We have a couple of 404s in https://github.com/weaveworks/grafanalib/runs/706550576:

ERROR	http://docs.grafana.org/reference/singlestat/
ERROR	http://docs.grafana.org/reference/singlestat/#coloring
ERROR	http://docs.grafana.org/reference/singlestat/#spark-lines
ERROR	http://docs.grafana.org/reference/singlestat/#value-to-text-mapping

**Comment by dholbach** [comment]
@marcusolsson Do you know where these docs went?

**Comment by oddlittlebird** [comment]
The Singlestat panel has been deprecated and replaced with the [Stat ](https://grafana.com/docs/grafana/latest/panels/visualizations/stat-panel/)panel, so the Singlestat content has been removed. I will add some aliases to the Stat topic in case other people still have links to Singlestat.

**Comment by oddlittlebird** [comment]
Though even that might not work, since you are linked to the old .org domain rather than the current .com domain.

**Comment by oddlittlebird** [comment]
Added this PR to hopefully address any other broken links: https://github.com/grafana/grafana/pull/25147

But honestly, these links are pretty old. The panel topics were moved out of the `reference` folder and into the `features` folder ages ago, and the docs moved from .org to .com months ago as well.

I recommend updating this library for the Stat panel.

**Comment by dholbach** [comment]
@oddlittlebird Thanks so much for the guidance and the fix for this. I'll make sure to link to the new home which redirects in #252 once grafana/grafana#25147 lands.

In a subsequent PR we should take a look at the Singlestat → Stat move.
