### ISSUE TITLE
Singlestat panel → Stat panel

### ISSUE THREAD

**Issue by dholbach** [weaveworks/grafanalib#253]
The Singlestat panel has been deprecated and replaced with the [Stat ](https://grafana.com/docs/grafana/latest/panels/visualizations/stat-panel/)panel, so the Singlestat content has been removed. I will add some aliases to the Stat topic in case other people still have links to Singlestat.

_Originally posted by @oddlittlebird in https://github.com/weaveworks/grafanalib/issues/251#issuecomment-634645460_

**Comment by matthewmrichter** [comment]
We'd like to leave SingleStat support in for some time, for the benefit of people such as us who are running older version. But we definitely need to add Stat as well.
