### ISSUE TITLE
SeriesOverride object needs @attr.s

### ISSUE THREAD

**Issue by gotoxu** [weaveworks/grafanalib#286]
Should [this object](https://github.com/weaveworks/grafanalib/blob/8f4b0fa48a2ff19e1af95d6298d36cabe28ca13d/grafanalib/core.py#L2638) need a class decorator `@attr.s`?

**Comment by hutchiko** [comment]
Yeah I have also encountered this. I ended up copying `SeriesOverride` (with `@attr.s` added) into my own module and then used that version rather than the one on `grafanalib`.

**Comment by JamesGibo** [comment]
You are correct, I have made this change and this will be included in the next release of grafanalib. 
Please feel free to submit patches for any errors you spot.
