### ISSUE TITLE
generate-dashboard output as a python post request

### ISSUE THREAD

**Issue by s0n00im** [weaveworks/grafanalib#308]
## What you expected to happen?
I used the output of  the following code. 

```
`from grafanalib.core import (
    Dashboard, Graph,
    OPS_FORMAT, Row,
    single_y_axis, Target, TimeRange, YAxes, YAxis
)
dashboard = Dashboard(
    title="Python generated dashboard",
    rows=[
        Row(panels=[
          Graph(
              title="Uptime",
              dataSource='Prometheus',
              targets=[
                  Target(
                    expr='sum by ()(increase(system_monitor_ms_test_results_count{producer=~"go|java|python|node", testresult="pass",consumer=~"go|java|python|node"}[1d]))/sum by ()(increase(system_monitor_ms_test_results_count{producer=~"go|java|python|node",consumer=~"go|java|python|node"}[1d]))',
                    legendFormat="{{ handler }}",
                    refId='A',
                  ),
              ],
              yAxes=single_y_axis(format=OPS_FORMAT),
          ),
        ]),
    ],
).auto_panel_ids()`
```

**This is the json output:**

`{
  "__inputs": [],
  "annotations": {
    "list": []
  },
  "description": "",
  "editable": true,
  "gnetId": null,
  "hideControls": false,
  "id": null,
  "links": [],
  "refresh": "10s",
  "rows": [
    {
      "collapse": false,
      "editable": true,
      "height": "250px",
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "cacheTimeout": null,
          "datasource": "Prometheus",
          "description": null,
          "editable": true,
          "error": false,
          "fill": 1,
          "grid": {
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "height": null,
          "hideTimeOverride": false,
          "id": 1,
          "interval": null,
          "isNew": true,
          "legend": {
            "alignAsTable": false,
            "avg": false,
            "current": false,
            "hideEmpty": false,
            "hideZero": false,
            "max": false,
            "min": false,
            "rightSide": false,
            "show": true,
            "sideWidth": null,
            "sort": null,
            "sortDesc": false,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 2,
          "links": [],
          "maxDataPoints": 100,
          "minSpan": null,
          "nullPointMode": "connected",
          "options": {
            "alertThreshold": true,
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "repeat": null,
          "seriesOverrides": [],
          "span": 12,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "datasource": "",
              "expr": "sum by ()(increase(system_monitor_ms_test_results_count{producer=~\"go|java|python|node\", testresult=\"pass\",consumer=~\"go|java|python|node\"}[1d]))/sum by ()(increase(system_monitor_ms_test_results_count{producer=~\"go|java|python|node\",consumer=~\"go|java|python|node\"}[1d]))",
              "format": "time_series",
              "hide": false,
              "instant": false,
              "interval": "",
              "intervalFactor": 2,
              "legendFormat": "{{ handler }}",
              "metric": "",
              "refId": "A",
              "step": 10,
              "target": ""
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Uptime",
          "tooltip": {
            "msResolution": true,
            "shared": true,
            "sort": 0,
            "value_type": "cumulative"
          },
          "transparent": false,
          "type": "graph",
          "xaxis": {
            "show": true
          },
          "yaxes": [
            {
              "decimals": null,
              "format": "ops",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": 0,
              "show": true
            },
            {
              "decimals": null,
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": 0,
              "show": true
            }
          ]
        }
      ],
      "repeat": null,
      "showTitle": false,
      "title": "New row"
    }
  ],
  "schemaVersion": 12,
  "sharedCrosshair": false,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-1h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "utc",
  "title": "Python generated dashboard",
  "uid": null,
  "version": 0
}
`
## How to reproduce it?

Next, i try to do a python post to my api using:
`response = requests.request("POST", url, data=jsonstring, headers=headers, verify=False)`

This gives me the following error:

**Response [{"fieldNames":["Dashboard"],"classification":"RequiredError","message":"Required"}] 422**

**Why is the dashboard field missing in the output of `generate-dashboard -o test.json example.dashboard.py`**
Is it because grafanalib is not compatible with the new grafana API. I tried to do a sample POST with postman to my api and it works fine with the following payload. 

`{
  "dashboard": {
    "id": null,
    "uid": null,
    "title": "python dashboard",
    "tags": [ "templated" ],
    "timezone": "browser",
    "schemaVersion": 16,
    "version": 0
  },
  "folderId": 0,
  "overwrite": false
}`

**Comment by JamesGibo** [comment]
Currently the `generate-dashboard` command only generates the dashboard json, which does not require the `dashboard`field. The generated JSON works fine if you use the import or provisioning upload methods.
https://grafana.com/docs/grafana/latest/dashboards/json-model/

If you want to use the grafana dashboard API you need to add the extra json fields you mentioned.
```json
"dashboard": {
    <grafanalib dashboard json>
  },
  "folderId": 0,
  "overwrite": false
```
Shown in https://grafana.com/docs/grafana/latest/http_api/dashboard/

PR's welcome to add a flag or something to the `generate-dashboard` command, so it generates JSON compatible with the grafana API.

**Comment by s0n00im** [comment]
hey, thank you. This worked for me. Let me try to take a dig at that PR.
