### ISSUE TITLE
missing alertRuleTags field in Alert object

### ISSUE THREAD

**Issue by alon-dotan-starkware** [weaveworks/grafanalib#316]
## What you expected to happen?
Try to create a grafana dashboard that contains several alerts contains notifiers and tags

## What happened?
Failed to sterilized the dashboard to JSON since the Alert object missing the field alertRuleTags

## How to reproduce it?
pass the alertRuleTags field to the Alert object

**Comment by JamesGibo** [comment]
Thank you for you interest in grafanalib.
I have added the alertRuleTags field to the graph panel, does this solve your issue?
If not, please could any comments on the linked PR?
