### ISSUE TITLE
Alert for Elasticsearch panel

### ISSUE THREAD

**Issue by dafna-starkware** [weaveworks/grafanalib#322]
Hi, 
I want to add an Alert object with AlertCondition for a Graph panel that uses ElasticsearchTarget. 
The AlertCondition should contain the ElasticsearchTarget but since ElasticsearchTarget doesn't inherit from Target I'm getting from the validator the error:
TypeError: ("'target' must be <class 'grafanalib.core.Target'> (got ElasticsearchTarget(

Is there another way to add an alert for a panel that uses Elasticsearch as the data source?

Thanks!
Dafna

**Comment by JamesGibo** [comment]
I have sub classed AlertCondition to support this, please try installing PR #324 and use ElasticsearchAlertCondition to see if this fixes your issue

**Comment by dafna-starkware** [comment]
I added another small change in order to enable the alert to change its' state - [334](https://github.com/weaveworks/grafanalib/pull/334)
