### ISSUE TITLE
Unable to use orderby Term in TermsGroupBy Function

### ISSUE THREAD

**Issue by ranushekhar** [weaveworks/grafanalib#384]
## What you expected to happen?
I want to apply orderby clause on Metric Function but in documentation, the process is not provided for the same. 
```
class grafanalib.elasticsearch.TermsGroupBy(field, id=0, minDocCount=1, order='desc',
orderBy='_term', size=0)
```
Here it is mentioned only default value _term but what if I want to chose MaxMetricAgg in orderby.

## What happened?
Instead of writing _term when I am writing MaxFieldname, it is throwing error.
```

Object
data:"{
    "root_cause": [
        {
            "type": "aggregation_execution_exception",
            "reason": "Invalid aggregation order path [_Max system.memory.hugepages.free]. The provided aggregation [_Max system.memory.hugepages.free] either does not exist, or is a pipeline aggregation and cannot be used to sort the buckets."

```

## How to reproduce it?
Request you to specify the steps to execute the same.
Please find below image for the panel that I am trying to achieve:
<img width="625" alt="1" src="https://user-images.githubusercontent.com/16058511/125297175-a32f4f00-e344-11eb-9afc-9aef6d94c47e.PNG">

My code:
title = KPI,
            dataSource='NFVi',
            targets=[ElasticsearchTarget(metricAggs=[MaxMetricAgg(field=KPI)],
                                         bucketAggs=[TermsGroupBy(field="agent.hostname",size=7,orderBy="_Maxsystem.memory.hugepages.free")]).auto_bucket_agg_ids()],
            )

**Comment by JamesGibo** [comment]
Hi, sorry for the slow reply been on holiday.

It appears that if you want to use a metric funtion to order by you need to use the value "2" in the config file. 
Please could you test this?
```
title = KPI,
dataSource='NFVi',
targets=[ElasticsearchTarget(metricAggs=[MaxMetricAgg(field=KPI)],
bucketAggs=[TermsGroupBy(field="agent.hostname",size=7,orderBy="2")]).auto_bucket_agg_ids()],
)
```

I have added some notes to function describing this, see #387
