### ISSUE TITLE
Publish documentation on readthedocs

### ISSUE THREAD

**Issue by jml** [weaveworks/grafanalib#4]
We already have a bit of API documentation. Would be good if that were made available on readthedocs.

**Comment by aknuds1** [comment]
Yes please, is it accessible anywhere else?

**Comment by jml** [comment]
Just what you see in the source code.

**Comment by aknuds1** [comment]
OK, I could definitely use some API documentation, because I'm wondering for example what the `refId` argument to `Target` means.

**Comment by jml** [comment]
Yeah, the problem is that Grafana itself doesn't document this stuff very well (or at least didn't when I wrote most of these classes).

`refId` is used by grafana to uniquely identify the target.

**Comment by aknuds1** [comment]
Thanks for letting me know about that @jml - would you mind shedding light on how one would use `refId` in practice so I just understand the purpose of it?

**Comment by jml** [comment]
Your best bet is to look at the JSON that Grafana itself generates and figure it out from there.

**Comment by aknuds1** [comment]
OK thanks @jml, I was looking at examples and couldn't see refId actually being referred to.

**Comment by dholbach** [comment]
I had a brief look at this, https://github.com/dholbach/grafanalib/tree/api-docs (reusing some of the bits we have for ignite, flux and wksctl). It's not quite there yet, but maybe somebody wants to take it further.

**Comment by dholbach** [comment]
A PR is up #204 - I'm looking forward to feedback and some help getting it over the finish line.
