### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by mkrakowitzer** [weaveworks/grafanalib#40]
Just a general comment, the example provided in the readme as well the example code on blog post https://www.weave.works/blog/grafana-dashboards-as-code/ do not work out of the box. As a new user this is very frustrating. I would like to be able to cargo cult the example code and it should work with generate-dashboard command. It may possibly make sense to include a more complete set of examples in an examples directory?

**Comment by jml** [comment]
Blog post is out of data due to recent changes to the library, and we're not going to go back and update it.

If you could provide the exact error you're seeing in the README, that would help fix the problem.

**Comment by mkrakowitzer** [comment]
Managed to get it working by installing the library directly from git
pip3 install --upgrade git+https://github.com/weaveworks/grafanalib.git

Thanks.
