### ISSUE TITLE
Support for colors in StatValueMapping?

### ISSUE THREAD

**Issue by milkpirate** [weaveworks/grafanalib#400]
Is ist possible to set colors for StatValueMappings? And if so where?

![image](https://user-images.githubusercontent.com/9251021/134369644-f996aefc-2eb3-40ca-9809-bf22e504440f.png)

Following doesnt work, but would be really nice!
```
            mappings=[
                StatRangeMapping('ON', startValue='1', endValue='300', color="dark-red"),
                StatValueMapping("OFF", mapValue='0')
            ]
```

**Comment by JamesGibo** [comment]
Hi

It looks like grafanalib does not support this currently, presume it is a new feature that has been added to grafana.
It should be trivial to add the `color` field to the output JSON.
Would you be able to raise a PR for this?

Previously I have achieved  changing the color using thresholds
```python
        thresholds=[
            core.Threshold('red', 0, 0.),
            core.Threshold('green', 1, 1.),
        ],
        mappings=[
            core.StatValueMapping('Offline', '0'),  # Value must a string
            core.StatValueMapping('Online', '1')
        ],
```

**Comment by milkpirate** [comment]
Ok, will write something. How do you run your tests? Do you use a framework? Pytest maybe?

**Comment by JamesGibo** [comment]
Thanks, we use pytest, only really to test that the library can serialise to JSON as the rest we can't really test for as its up to Grafana and its schema.

There is a makefile that makes running the tests easier. 
```
make test
```

**Comment by milkpirate** [comment]
Could you please review this: https://github.com/weaveworks/grafanalib/pull/401
I am pretty sure I did something wrong because the color does not end up in the final JSON at all :/
