### ISSUE TITLE
Jsonnet version?

### ISSUE THREAD

**Issue by jml** [weaveworks/grafanalib#43]
This isn't a bug, so much as a question for any grafanalib users who might be watching.

How would you feel about a jsonnet version of grafanalib?

Prompted by [recent announcement](https://blog.heptio.com/ksonnet-intro-43f6183a97a6) of [ksonnet](http://ksonnet.heptio.com/).

**Comment by jml** [comment]
It would mean instead of doing dashboards in Python, they'd be done in a JSON-like language. I'd also like to try https://github.com/dhall-lang/dhall-lang/, which would bring the advantage of type checking.

However, I'm probably going to stick with Python for the foreseeable future.

**Comment by aknuds1** [comment]
Thanks, good to know!

**Comment by jml** [comment]
Turns out someone's already done this: https://github.com/grafana/grafonnet-lib
