### ISSUE TITLE
AlertList fails on auto_panel_ids

### ISSUE THREAD

**Issue by jakub-m** [weaveworks/grafanalib#441]
## What you expected to happen?

AlertList should work with Dashboard  using `auto_panel_ids`

## What happened?

AlertList fails when the overlapping Dashboard runs `auto_panel_ids`. I suppose this is because AlertList does not inherit Panel, while it should.

## How to reproduce it?

1. Create a `Dashboard`
2. Add `AlertList` to the dashboard's `panels`
3. Run dashboard `auto_panel_ids()`

```
  File "/usr/local/lib/python3.7/site-packages/grafanalib/core.py", line 1110, in auto_panel_ids
    return self._map_panels(set_id)
  File "/usr/local/lib/python3.7/site-packages/grafanalib/core.py", line 1094, in _map_panels
    panels=[p._map_panels(f) for p in self.panels]
  File "/usr/local/lib/python3.7/site-packages/grafanalib/core.py", line 1094, in <listcomp>
    panels=[p._map_panels(f) for p in self.panels]
AttributeError: 'AlertList' object has no attribute '_map_panels
```

**Comment by JamesGibo** [comment]
The reason that when created `AlertList` class did not inherit the `Panel` class is that it has a lot of functionality that is not present in the Alertlist panel when i looked at it. 

Please could you try adding the following function to the `AlertList` class to see if it fixes your issue?

```python
def _map_panels(self, f):
        return f(self)
```

**Comment by jakub-m** [comment]
Yes, this is exactly what I did to fix the issue. I added such a piece of code to the descendant class and used the descendant.
