### ISSUE TITLE
Graph object does not support decimals

### ISSUE THREAD

**Issue by mongrelion** [weaveworks/grafanalib#45]
There is a use case where the displayed value on a `Graph` needs to have as specific `decimal` value set to it but the current implementation does not allow that.

**Comment by jml** [comment]
Can you please post a minimal example reproducing the problem, together with what you saw and what you hoped to see instead?

**Comment by fho** [comment]
@mongrelion do you maybe mean the number of decimal places on the Axis labels?

I created a PR for it: https://github.com/weaveworks/grafanalib/pull/88

**Comment by jml** [comment]
If I don't hear otherwise, will close optimistically next Monday.

**Comment by mongrelion** [comment]
I confirm that PR #88 fixes this.
