### ISSUE TITLE
Example Dashboard doesn't work with default Prometheus install

### ISSUE THREAD

**Issue by reubano** [weaveworks/grafanalib#458]
## What you expected to happen?

Example dashboard to work with default Prometheus install

## What happened?

Got an empty  dashboard

## How to reproduce it?

Follow the [Writing dashboards](https://grafanalib.readthedocs.io/en/stable/getting-started.html#writing-dashboards) guide. [This online guide](https://medium.com/swlh/create-grafana-dashboards-with-python-14a6962eb06c) worked however.

**Comment by JamesGibo** [comment]
Hi, I have updated the example dashboard to work with default Grafana install and Prometheus.
Would you be able to test this works for you?
