### ISSUE TITLE
Parameterise Template class fields

### ISSUE THREAD

**Issue by mongrelion** [weaveworks/grafanalib#46]
Currently the `Template` class only exposes certain fields (https://github.com/weaveworks/grafanalib/blob/8bbdbc80c0cade117d0f333267d1a9bf3400ad14/grafanalib/core.py#L370-L409) but others are given a default value that may not apply for each use case.
The class should allow for these parameters to be overwritten.

**Comment by dholbach** [comment]
@JamesGibo says:
> It looks like most params can be overwritten now
> https://github.com/weaveworks/grafanalib/blob/f18f3c62938d2e43857f0b7a41a20bc2f3ecbf87/grafanalib/core.py#L694

Do you feel we can close this issue now?
