### ISSUE TITLE
Way to configure Shared Tooltip for dashboard

### ISSUE THREAD

**Issue by jamesatkin-pexip** [weaveworks/grafanalib#476]
## What you expected to happen?
I expected an option to configure a dashboard to use "Shared Tooltip", seen below in the UI.

![image](https://user-images.githubusercontent.com/70574589/159733269-bb9161a6-584a-43d8-ab22-366e9e377e73.png)

## What happened?
There's no option for this in the `Dashboard` class.

## Additional info

I did try writing a wrapper for this to hack it into the JSON output:

```python
class MyDashboard(Dashboard):
    graphTooltip = 2

    def to_json_data(self):
        parent_dashboard = super().to_json_data()
        parent_dashboard["graphTooltip"] = self.graphTooltip
        return parent_dashboard
```

Putting this through the generator does produce the correct value (`"graphTooltip": 2`) in the output:

```json
{
  "__inputs": [],
  "annotations": {
    "list": []
  },
  "description": "",
  "editable": true,
  "gnetId": null,
  "graphTooltip": 2,
  "hideControls": false,
   ...
}
```

However, importing this JSON into Grafana on the UI doesn't retain the option, and the dashboard doesn't have a shared tooltip.

**Comment by mharbison72** [comment]
I bet you need to set the `schemaVersion` on the dashboard object to something newer.  12 is getting set by default, but my local grafana 8.5.2 is generating dashboards with 36 as the value.

I'm curious what the strategy to handle this should be- there are at least a handful of attributes that are being created by grafanalib that are no longer created by grafana, and it would be nice to skip the old stuff if it's not needed.  But I assume bumping the default to a new value would cause breaking people with older grafana installations, and not be accepted.

**Comment by aj-sx** [comment]
dashboard.schemaVersion needs to be set to 14, this is where the feature got probably introduced.
