### ISSUE TITLE
How can I see the dashbords with Grafanalib ?

### ISSUE THREAD

**Issue by youssefbenfarhat** [weaveworks/grafanalib#484]
Hello, 
I'm new with Grafanalib. I'm trying to understand how to display the charts and dashboards with Grafanalib.

For example this is my code, how can I see the results:

from grafanalib.core import *
from graphtoolss import *
from grafanalib._gen import print_dashboard

rows_code = [Row(panels=[
                 singleQueryGraph(
                     "1-graph",
                     "rate(prometheus_http_requests_total[5m])",
                     "{{ handler }}"
                     ),
                 singleQueryGraph(
                     "2-graph",
                     "rate(prometheus_http_requests_total[5m])",
                     "{{ handler }}"
                     )
                ],
                )
              ]

dashboard = Dashboard(
        version=2,
        tags=["Grafanalib"],
        title="Test with two graphs",
        uid="test",
        rows=rows_code,
        ).auto_panel_ids()

print("heeyy",dashboard.to_json_data())

... 
print_dashboard(dashboard)

**Comment by JamesGibo** [comment]
Hi,

Please have a look at the getting started guide, specifically using `generate-dashboard -o frontend.json example.dashboard.py` to generate the JSON file to be uploaded to Grafana. 
https://grafanalib.readthedocs.io/en/stable/getting-started.html

**Comment by JamesGibo** [comment]
Let me know if you need anymore help after reading the guide.

**Comment by youssefbenfarhat** [comment]
Hello @JamesGibo,

Sorry for my late response but I always get the 404 - b'{"message":"Not found"}\n' error 

I changed the grafana_api_key variable with my Api key and the grafana server with mine also.

**Comment by JamesGibo** [comment]
As there has been no further response, I am going to close this issue, please re-open if you have not managed fix your issue.
