### ISSUE TITLE
Release timeline for 0.6.3

### ISSUE THREAD

**Issue by rishavjayswal** [weaveworks/grafanalib#485]
We wanted to use the legendCalc feature so that we can display different arithmetic functions like mean, min and max for our legends. 
We see in the change log that this feature was part of 0.6.3 version. But we are not able to install it through pip and apparently its not released yet.

Can you please give us a timeline on its release? The change log was updated two weeks ago. 😅

**Comment by JamesGibo** [comment]
Hi, I can push a new release shortly for you.

**Comment by JamesGibo** [comment]
New release is live
