### ISSUE TITLE
[question] Utility to convert json export into code?

### ISSUE THREAD

**Issue by jarlva** [weaveworks/grafanalib#521]
Hi, is there a way to convert an existing panel/dashboard into python code (or similar)? The intent is to jump-start dashboard-as-code for existing dashboards. Thus saving conversion time.

**Comment by OscarVanL** [comment]
Looks like this issue might overlap with this one.

https://github.com/weaveworks/grafanalib/issues/75

**Comment by JamesGibo** [comment]
Closing as duplicate and not something that is currently being worked on, but a welcome feature if someone wants to work on it
