### ISSUE TITLE
Generate dashboard json from inside Python

### ISSUE THREAD

**Issue by vsoch** [weaveworks/grafanalib#538]
Hi! I'm new to this project and Grafana, and I'm wondering if it's possible to reproduce:

```console
generate-dashboard -o frontend.json example.dashboard.py
```

But from within Python. My use case is wanting to start with my data file, and have my own client to output the json file. E.g.,:

```console
$ python myscript.py transform my-custom-input.cali
# generates the final dashboard.json
```
Instead of needing to do:

```console
$ python myscript.py transform my-custom-input.cali -> write temporary python file --> generate-dashboard
```

E.g., I can hack sys.argv and write my generated python file to a temporary location first (this bit)

```python
...
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(generate_dashboard_script())
```

But it would be really nice to just generate that code, and then the json from the same script. Is this possible (and maybe I'm missing the docs for it somewhere?) thank you!

**Comment by JamesGibo** [comment]
Yeah, there is an example of doing just that here:

https://github.com/weaveworks/grafanalib/blob/main/grafanalib/tests/examples/example.upload-dashboard.py

**Comment by vsoch** [comment]
Perfect, thank you!
