### ISSUE TITLE
AlertCondition object missing useNewAlerts attribute

### ISSUE THREAD

**Issue by alon-dotan-starkware** [weaveworks/grafanalib#545]
looking at https://github.com/weaveworks/grafanalib/blob/c9a77d481da8d76a91ad92efb1a155d6dae8a34d/grafanalib/core.py#L1192
and https://github.com/weaveworks/grafanalib/blob/c9a77d481da8d76a91ad92efb1a155d6dae8a34d/grafanalib/core.py#L1215 its possible to see there is use of self.useNewAlerts but AlertExpression don't have this attribute

**Comment by JamesGibo** [comment]
This field is added dynamically when you use the AlertExpression class.

https://github.com/weaveworks/grafanalib/blob/c9a77d481da8d76a91ad92efb1a155d6dae8a34d/grafanalib/core.py#L1312

Adding a new variable to an instance of a class is possible in python
https://docs.python.org/2/tutorial/classes.html#odds-and-ends

We could add `useNewAlerts` as a variable to the AlertCondition class to avoid confusion, if there is an actual issue you are facing?

**Comment by jimbolimbo13** [comment]
Thanks for the tip, @JamesGibo. My current workaround is to declare AlertCondition as a variable then set `useNewAlerts` directly:

```
alertCond = AlertCondition( <stuff> )
alertCond.useNewAlerts = False
```

Use case is to generate something for the extraJson field in my dashboard panels so I have the alerts show up there.

**Comment by olha-honcharuk** [comment]
@JamesGibo if you can add `useNewAlerts` as a variable to the `AlertCondition` class with the default value for the latest Grafana - it would be very helpful for us. We are using `AlertCondition` outside of `AlertExpression ` as the parameter to [`Alert`]( https://grafanalib.readthedocs.io/en/stable/api/grafanalib.html#grafanalib.core.Alert)

**Comment by ali-essam** [comment]
@JamesGibo @olha-honcharuk I just pushed a fix PR addressing this issue as I was facing it too. I chose to default to False though for backwards compatibility since it's overridden in the code anyways for 8.x and 9.x. PTAL and let me know your thoughts!

**Comment by JamesGibo** [comment]
Fixed in https://github.com/weaveworks/grafanalib/pull/584
