### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by jml** [weaveworks/grafanalib#56]
I've got a checklist, but it's still pretty fraught with human error. Would like to just push a button. Probably should use a docker image.

**Comment by dholbach** [comment]
Maybe https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ is easy to set up for us now?

**Comment by errordeveloper** [comment]
@dholbach let me know how are you getting on, happy to help out :)

**Comment by dholbach** [comment]
Yeah, I was thinking of following the steps on https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ once I have access to the controls and potentially get out [0.5.5](https://github.com/weaveworks/grafanalib/milestone/2) as a test.

cc @matthewmrichter and @bboreham

**Comment by dholbach** [comment]
First test at https://github.com/dholbach/grafanalib/runs/446202668 looks positive. If all goes well, we can re-target this issue to 0.5.5.

**Comment by errordeveloper** [comment]
Glad to hear that!
