### ISSUE TITLE
Fix bug with dict

### ISSUE THREAD

**Issue by JamesGibo** [weaveworks/grafanalib#590]
Replace everywhere `default={}` or `default=[]` used with `factory=dict` or `factory=list` instead, as if one value changed all change.

https://www.attrs.org/en/stable/api-attr.html#attr.ib

```
>>> import attr
>>> @attr.s
... class X:
...     d = attr.ib(default={})
...
>>> a = X()
>>> b = X()
>>> a.d['test']='test'
>>> b
X(d={'test': 'test'})
>>>
```

Thanks to @ilia-ilin-jiji for spotting

**Comment by ujwalkumar1995** [comment]
Hey @JamesGibo 
I would like to work on this. Could you please assign?
