### ISSUE TITLE
Are there plans to release a new version?

### ISSUE THREAD

**Issue by gmmcal** [weaveworks/grafanalib#636]
Last release of package was over 1 year ago and there are many nice features on master that are not released yet (specially on Timeseries dashboard, which I am porting from Graph at this moment). In fact, there are [52 unreleased commits](https://github.com/weaveworks/grafanalib/compare/v0.7.0...main)

I could use code from master branch, but there is a "risk" that I am using something untested, which is not amazing.

At first, I thought package was unmaintained because of last release date, but commits on master does show it is not the case and that is awesome.

Thanks

**Comment by gburton1** [comment]
@JamesGibo I see that you are the last maintainer on this project. My org uses grafanalib pretty extensively; if you are spread thin on other projects and need reinforcement on some basics like releases and dependency updates, we might be able to help. Or if you sense that deprecation could be in the cards for grafanalib, that would also be a good data point to be aware of.

**Comment by JamesGibo** [comment]
Hi All, sorry for the absence, I have just started a new job so been focusing on that.

I don't think deprecation is on the card fro grafanlib just yet, there are many good features, some active development and still nothing concrete from Grafana around schemas that makes me think there is a better alternative for Grafana Dashboards as code.

If you like you or anyone else tha uses grafanalib would be able to offer some time to help maintain grafanalib by creating releases and merging PRs that would be much appreciated. Maybe we could chat about this on Slack? Please reach out!
If you do want to become a maintainer then I will have to check with someone at Weaveworks to add you as I do not have the required permissions.

**Comment by JamesGibo** [comment]
Regarding releases, I hopefully should have sometime towards the end of this week to prepare and make a release.

**Comment by gmmcal** [comment]
At this moment, I can't join as maintainer due to focus on other priorities, both personal and professional.

And, to be clear, I did not want to force a release if things are not ready. I know that a maintainer job is hard.

If something changes on my end, I can ping back in this. This package has saved me tons of debug/jinja hours already and I really wish it does not die.

**Comment by JamesGibo** [comment]
Release has been made!
Hope this helps and that you can join as a maintainer at some point in the future, the help would be much appreciated.
