### ISSUE TITLE
Specify target option like intervalFactor in PromGraph

### ISSUE THREAD

**Issue by gaelL** [weaveworks/grafanalib#65]
Looking at https://github.com/weaveworks/grafanalib/blob/master/grafanalib/prometheus.py#L8

The `PromGraph` function have a fix call to `Target` to insert `expressions` with only `expr, legend, refId=refId`.

In my case I need to also specify other parameters like `intervalFactor`.

WDYT about change `expressions` `list` of `tuple` arg by `list` of `dict` to allow to specify every `Target` args ?

If needed we could let both behavior compatible by checking if the list contain `tuple` or `dict`.

Something like 

```
    if all(isinstance(expr, dict) for expr in expressions):
        targets = [ 
            G.Target(refId=refId, **args)
            for (args, refId) in zip(expressions, letters)]
    else:
        targets = [ 
            G.Target(expr, legend, refId=refId)
            for ((legend, expr), refId) in zip(expressions, letters)]
```

Could do the job

**Comment by jml** [comment]
Definitely want to preserve backwards compatibility with current API, and definitely want to keep the succinct syntax for the current case (which I believe is the most common). In favour of allowing specifying via list of dicts.

**Comment by gaelL** [comment]
I created #66 related to that if it can help you.
