### ISSUE TITLE
[Question] Are there plans to support he new Alerting Provisioning API from Grafana?

### ISSUE THREAD

**Issue by nambrosini17** [weaveworks/grafanalib#660]
## What you expected to happen?
I expected to be able to use `AlertRules` to create new style alerts as specified by the official docs here https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/

## What happened?
I noticed examples are targeted to v8 and v9 of the alerts 
- https://github.com/weaveworks/grafanalib/blob/main/grafanalib/tests/examples/example.upload-alerts.py
- https://github.com/weaveworks/grafanalib/blob/main/grafanalib/tests/examples/example.alertsv9.alertgroup.py
- https://github.com/weaveworks/grafanalib/blob/main/grafanalib/tests/examples/example.alertsv8.alertgroup.py

but there's no support for the new type of alerts available since grafana v10 https://grafana.com/blog/2024/03/06/grafana-10.4-release-all-the-latest-features/#grafana-alerting
Since grafana v11 release, these are the only supported type of alerts.

## How to reproduce it?
Run https://github.com/weaveworks/grafanalib/blob/main/grafanalib/tests/examples/example.upload-alerts.py and print the json output after `get_alert_json` call. When comparing the request structure one can notice it will fail creating alerts in grafana v11.

I understand this is an open source project with no financial support so there's no expectation from me that library mantainers should support this new version. I just want to check if there's a roadmap of support or if the library is considered in mantainance mode without room for new features.  Would you consider pull requests adding this feature?

**Comment by morsik** [comment]
@nambrosini17 given that [Weaveworks company doesn't exist anymore](https://thenewstack.io/end-of-an-era-weaveworks-closes-shop-amid-cloud-native-turbulence/), I would suspect that there won't be any ongoing features added :(
