### ISSUE TITLE
How does one build grafanalib?

### ISSUE THREAD

**Issue by aknuds1** [weaveworks/grafanalib#70]
I can't tell how to build grafanalib, especially generate-dashboards from the README. How should one do it?

**Comment by jml** [comment]
It's a normal Python project. You don't build it, you install it with `pip`..

**Comment by jml** [comment]
What are you trying to do?

**Comment by aknuds1** [comment]
@jml It's for the purpose of trying to hack on it.

**Comment by jml** [comment]
```console
$ virtualenv .env
$ . .env/bin/activate
$ pip install -e .
```

**Comment by aknuds1** [comment]
Thanks @jml - gonna give it a whirl!

**Comment by aknuds1** [comment]
Worked, except I used this second command: `. ./.env/bin/activate`! Thanks!
