### ISSUE TITLE
Make generate-dashboard(s) into a module?

### ISSUE THREAD

**Issue by aknuds1** [weaveworks/grafanalib#72]
First of all, thanks for creating this project! I am wondering though if the generate-dashboard/s scripts could be made into a module (in addition to the scripts) so one could generate dashboards from one's own scripts?

I could contribute a PR if you think it's a good idea.

**Comment by jml** [comment]
They already are in a module: https://github.com/weaveworks/grafanalib/blob/master/grafanalib/_gen.py

I have no objection to making that module public, but I'd like the following functions to remain private:
- `get_json_path`
- `dashboard_path`
- `generate_dashboards`
- `generate_dashboard`
- `run_script`
- `generate_dashboards_script`
- `generate_dashboard_script`

**Comment by aknuds1** [comment]
Thanks, I might look into it :)
