### ISSUE TITLE
Question: Prometheus only?

### ISSUE THREAD

**Issue by shezaan** [weaveworks/grafanalib#78]
Does this library only work with prometheus? We use Telegraf and collect metrics and events into InfluxDB. Would it work with those?

Thanks in advance!

**Comment by jml** [comment]
There's support for other things (ISTR reviewing PRs for Zabbix & OpenTSDB). All of the Prometheus stuff is in `grafanalib.prometheus`, so if you avoid that module, you'll be fine. Not sure about Telegraf and InfluxDB specifically.

**Comment by fho** [comment]
It seems not to work with elasticsearch currently.

Elasticsearch queries are defined as value for  a`query` field in the JSON file.
The `Target` class of the library does not have a `query` field.  It only supports to define the query in an `expr` field which does not work with a elasticsearch datasource

**Comment by buroa** [comment]
Probably fixed with my issue and PR #145

**Comment by qmnonic** [comment]
PR https://github.com/weaveworks/grafanalib/pull/182 addresses using influxdb directly, adding an InfluxDBTarget (allowing simple raw queries).

**Comment by JamesGibo** [comment]
PR #182 now merged, so should be fixed.
Let us know if you have any issues
