### ISSUE TITLE
Move PromGraph to core module

### ISSUE THREAD

**Issue by jml** [weaveworks/grafanalib#8]
Prometheus is a super common use case. Current `PromGraph` conflates Weave config with using Prometheus.

- Get rid of the hard-coded data source
- Move function to core
- Re-export from `_weave` using hard-coded data source

**Comment by dmajere** [comment]
I think you should move it to `prometheus.py` or something similar.
Classes related to Opentsdb are in opentsdb.py, to zabbix are in zabbix.py, so, Prometheus ones should be in prometheus.py
