### ISSUE TITLE
Any plans for 1.0.0?

### ISSUE THREAD

**Issue by meng-tian** [weaveworks/grafanalib#85]
First of all, thanks for this tremendously helpful library.

When do you plan to have a 1.0.0 release?

**Comment by jml** [comment]
No current plans—why do you ask?

**Comment by meng-tian** [comment]
It is mentioned in README that this repository is still under active development and you will try hard to maintain backward compatibility. I regard 1.0.0 as a stable release so I can safely use this library.

**Comment by jml** [comment]
There are still a couple of possible compatibility-breaking changes in the pipeline.

That said, we are using semantic versioning, so if you pin to, say, `0.3.*` you can rely on us not breaking anything.

For me, 1.0 will mean no backwards compatible changes anticipated plus a certain level of feature completeness.

**Comment by jml** [comment]
I've created https://github.com/weaveworks/grafanalib/milestone/1 to outline what I think needs to happen for 1.0

**Comment by meng-tian** [comment]
The milestone looks great! 

It's glad to know that you maintain backwards compatibility in patch version during the initial development. 

Thank you again for your help.
