### ISSUE TITLE
Update docs re data source for new grafana releases

### ISSUE THREAD

**Issue by jml** [weaveworks/grafanalib#94]
ISTR new grafana releases have better ways of specifying the data source. We should find those and refer to them in the docs, promoting gfdatasource only for older versions.

**Comment by jml** [comment]
https://github.com/grafana/grafana/pull/9504

**Comment by leth** [comment]
Here's the docs page: http://docs.grafana.org/administration/provisioning/#datasources

**Comment by errordeveloper** [comment]
I've been able to use it in workshop our environment, see https://github.com/errordeveloper/k9c/blob/5484fa4dc4025a8427df4f13b1efec77670c786b/modules/weavecloud/grafana.yaml.
